AlvesMello_IntraNet/Areas/Admin/Controllers/AdminDepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AlvesMello_IntraNet.Context;
using AlvesMello_IntraNet.Models;
using Microsoft.AspNetCore.Authorization;
using ReflectionIT.Mvc.Paging;

namespace AlvesMello_IntraNet.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles="Admin")]
    public class AdminDepartmentsController : Controller
    {
        private readonly AppDbContext _context;

        public AdminDepartmentsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminDepartments
        public async Task<IActionResult> Index(string filter, int pagindex = 1, string sort = "Name")
        {
            var result = _context.Departments
                    .AsQueryable();

            if (!string.IsNullOrWhiteSpace(filter))
            {
                result = result.Where(p => p.Name.Contains(filter));
            }

            var model = await PagingList.CreateAsync(result, 5, pagindex, sort, "Name");
            model.RouteValue = new RouteValueDictionary { { "filter", filter } };
            return View(model);
        }

        // GET: Admin/AdminDepartments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .FirstOrDefaultAsync(m => m.DepartmentId == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // GET: Admin/AdminDepartments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminDepartments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DepartmentId,Color,Name,Description")] Department department)
        {
            if (ModelState.IsValid)
            {
                _context.Add(department);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Admin/AdminDepartments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // POST: Admin/AdminDepartments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DepartmentId,Color,Name,Description")] Department department)
        {
            if (id != department.DepartmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.DepartmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Admin/AdminDepartments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .FirstOrDefaultAsync(m => m.DepartmentId == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Admin/AdminDepartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Departments == null)
            {
                return Problem("Entity set 'AppDbContext.Departments'  is null.");
            }
            var department = await _context.Departments.FindAsync(id);
            if (department != null)
            {
                _context.Departments.Remove(department);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
          return _context.Departments.Any(e => e.DepartmentId == id);
        }
    }
}

AlvesMello_IntraNet/Areas/Admin/Views/AdminDepartments/Create.cshtml
@model AlvesMello_IntraNet.Models.Department

@{
	ViewData["Title"] = "Adicionar Departamento";
}

<h1>Adicionar Departamento</h1>

<hr />

<div class="container">
	<div class="row">
		<div class="col-12">
			<form asp-action="Create">
				<div asp-validation-summary="ModelOnly" class="text-danger" />
				<div class="form-group d-flex">
					<div>
						Cor
						<input asp-for="Color" type="color" class="form-control form-control-color" title="Escolha a cor" />
						<span asp-validation-for="Color" class="text-danger"></span>
					</div>
					<div class="col-11">
						<label asp-for="Name" class="control-label"></label>
						<input asp-for="Name" class="form-control" />
						<span asp-validation-for="Name" class="text-danger"></span>
					</div>
				</div>

				<div class="form-group col-12">
					<label asp-for="Description" class="control-label"></label>
					<textarea asp-for="Description" class="form-control" rows="8"></textarea>
					<span asp-validation-for="Description" class="text-danger"></span>
				</div>
				<br />

				<div class="col-12">
					<div class="d-flex">
						<div class="col-1">
							<div class="form-group">
								<input type="submit" value="Adicionar" class="btn btn-primary" />
							</div>
						</div>
						<div class="col-1">
							<div>
								<a class="btn btn-secondary" asp-area="Admin" asp-controller="AdminDepartments" asp-action="Index">Voltar</a>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

AlvesMello_IntraNet/Areas/Admin/Views/AdminDepartments/Delete.cshtml
@model AlvesMello_IntraNet.Models.Department

@{
    ViewData["Title"] = "Deletar Departamento";
}

<h1>Deletar Departamento</h1>

<h3>Você tem certeza que deseja deletar esse Departamento?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Name)
		</dt>
		<dd class="col-sm-10">
			<div class="d-flex text-center text-light">
				<div class="rounded-pill p-2" style="background-color: @Html.DisplayFor(model => model.Color)">
					@Html.DisplayFor(model => model.Name)
				</div>
			</div>
		</dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DepartmentId" />
        <input type="submit" value="Deletar" class="btn btn-danger" />
        <a class="btn btn-secondary" asp-action="Index">Voltar para a Listagem</a>
    </form>
</div>

AlvesMello_IntraNet/Areas/Admin/Views/AdminDepartments/Details.cshtml
@model AlvesMello_IntraNet.Models.Department

@{
	ViewData["Title"] = "Detalhes do Departamento";
}

<h1>Detalhes do Departamento</h1>

<div>
	<h4>Id do Departamento: @Model?.DepartmentId</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Name)
		</dt>
		<dd class="col-sm-10">
			<div class="d-flex text-center text-light">
				<div class="rounded-pill p-2 " style="background-color: @Html.DisplayFor(model => model.Color)">
					@Html.DisplayFor(model => model.Name)
				</div>
			</div>
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Description)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Description)
		</dd>
	</dl>
</div>
<div>
	<a class="btn btn-dark" asp-action="Edit" asp-route-id="@Model?.DepartmentId">Editar Departamento</a>
	<a class="btn btn-secondary" asp-action="Index">Voltar para a Listagem</a>
</div>

AlvesMello_IntraNet/Areas/Admin/Views/AdminDepartments/Edit.cshtml
@model AlvesMello_IntraNet.Models.Department

@{
	ViewData["Title"] = "Editar Departamento";
}

<h1>Editar Departamento</h1>
<hr />


<div class="container">
	<div class="row">
		<div class="col-12">
			<form asp-action="Edit">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<input type="hidden" asp-for="DepartmentId" />

				<div class="form-group d-flex">
					<div>
						Cor
						<input asp-for="Color" type="color" class="form-control form-control-color" title="Escolha a cor" value="@Model.Color" />
					</div>
					<div class="col-11">
						<label asp-for="Name" class="control-label"></label>
						<input asp-for="Name" class="form-control" />
						<span asp-validation-for="Name" class="text-danger"></span>
					</div>
				</div>
				<div class="form-group col-12">
					<label asp-for="Description" class="control-label"></label>
					<textarea asp-for="Description" class="form-control" rows="8"></textarea>
					<span asp-validation-for="Description" class="text-danger"></span>
				</div>
				<br />

				<div class="col-12">
					<div class="d-flex">
						<div class="col-1">
							<div class="form-group">
								<input type="submit" value="Salvar" class="btn btn-primary" />
							</div>
						</div>
						<div class="col-1">
							<div>
								<a class="btn btn-secondary" asp-area="Admin" asp-controller="AdminDepartments" asp-action="Index">Voltar</a>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<br />

AlvesMello_IntraNet/Areas/Admin/Views/AdminDepartments/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<AlvesMello_IntraNet.Models.Department>

@{
	ViewData["Title"] = "Listagem de Departamentos";
}

<h1>Departamentos</h1>

<form method="get" class="form-inline">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="input-group">
					<div class="input-group-btn">
						<button type="button" class="btn btn-dark dropdown-toggle" data-toggle="dropdown"> Nome <span class="caret"></span></button>

						<ul class="dropdown-menu">
							<li>
								<a>Nome</a>
							</li>
						</ul>
					</div>

					<div class="form-group col-10">
						<input name="filter" type="text" class="form-control" maxlength="100" value="@Model.RouteValue["Filter"]">
					</div>

					<div class="input-group-btn">
						<button type="submit" class="btn btn-danger">
							<image src="/images/Search.png"></image>
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>
<br />

<div>
	<vc:pager paging-list="@Model"></vc:pager>
</div>

<div class="row">
	<div class="col-md-12">
		<table class="table">
			<thead>
				<tr>
					<th>
						@Html.DisplayNameFor(model => model.Name)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.Description)
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td style="color: white">
							<div class="d-flex justify-content-evenly text-center">
								<div class="rounded-pill p-2 " style="background-color: @item.Color">
									@Html.DisplayFor(modelItem => item.Name)
								</div>
							</div>
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Description)
						</td>
						<td>
							<div class="d-flex flex-wrap justify-content-evenly">
								<div>
									<a class="btn btn-dark" asp-action="Edit" asp-route-id="@item.DepartmentId">Editar</a>
								</div>
								<div>
									<a class="btn btn-secondary" asp-action="Details" asp-route-id="@item.DepartmentId">Detalhes</a>
								</div>
								<div>
									<a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.DepartmentId">Deletar</a>
								</div>
							</div>
						</td>
					</tr>
				}
			</tbody>
		</table>

		<div class="row">
			<div class="col-6">
				<a class="btn btn-success" asp-action="Create">
					Adicionar Departamento
				</a>
			</div>

			<div class="col-6 d-flex justify-content-end">
				Total de Departamentos: @Model.TotalRecordCount
			</div>
		</div>
	</div>
</div>