AlvesMello_IntraNet/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace AlvesMello_IntraNet.Controllers
{
	public class ContactController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

AlvesMello_IntraNet/Controllers/SiteController.cs
using AlvesMello_IntraNet.Models;
using AlvesMello_IntraNet.Repositories.Interfaces;
using AlvesMello_IntraNet.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AlvesMello_IntraNet.Controllers
{
    public class SiteController : Controller
    {
        private readonly ISiteRepository _siteRepository;

        public SiteController(ISiteRepository siteRepository)
        {
            _siteRepository = siteRepository;
        }

        public IActionResult List(string department)
        {
            IEnumerable<Site> sites;
            string currentDepartment = string.Empty;

			if (string.IsNullOrEmpty(department))
			{
                sites = _siteRepository.Sites.OrderBy(s => s.SiteId);
                currentDepartment = "Todos os Sites";
			}
			else
			{
                sites = _siteRepository.Sites
                    .Where(s => s.Department.Name.Equals(department))
                    .OrderBy(s => s.Name
                );

                currentDepartment = department;
			}

            var sitesListViewModel = new SiteListViewModel
            {
                Sites = sites,
                CurrentDepartment = currentDepartment
            };

            return View(sitesListViewModel);
        }

        public IActionResult Details(int siteId)
		{
            var site = _siteRepository.Sites
                .FirstOrDefault(s => s.SiteId.Equals(siteId)
            );

            return View(site);
		}

        public ViewResult Search(string searchString)
        {
            IEnumerable<Site> sites;
            string currentDepartment = string.Empty;

            if (string.IsNullOrEmpty(searchString))
            {
                sites = _siteRepository.Sites.OrderBy(s => s.SiteId);
                currentDepartment = "Todos os Sites";
            }
            else
            {
                sites = _siteRepository.Sites
                        .Where(s => s.Name.ToLower().Contains(searchString.ToLower())
                );

                if (sites.Any())
                {
                    currentDepartment = "Sites";
                }
                else
                {
                    currentDepartment = "Nenhum Site foi Encontrado!";
                }
            }
            return View("~/Views/Site/List.cshtml", new SiteListViewModel
            {
                Sites = sites,
                CurrentDepartment = currentDepartment
            });
        }
    }
}

AlvesMello_IntraNet/Views/Shared/_Carousel.cshtml
<div id="carouselAplicativos" class="carousel carousel-dark slide" data-bs-ride="carousel">
	<div class="carousel-indicators">
		<button type="button" data-bs-target="#carouselAplicativos" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
		<button type="button" data-bs-target="#carouselAplicativos" data-bs-slide-to="1" aria-label="Slide 2"></button>
		<button type="button" data-bs-target="#carouselAplicativos" data-bs-slide-to="2" aria-label="Slide 3"></button>
	</div>
	<div class="carousel-inner">
		<div class="carousel-item active" data-bs-interval="5000">
			<img src="/images/Ecac.png" class="d-block w-100 h-100" alt="...">
			<div class="carousel-caption d-none d-md-block">
				<h5>First slide label</h5>
				<p>Some representative placeholder content for the first slide.</p>
			</div>
		</div>
		<div class="carousel-item" data-bs-interval="5000">
			<img src="/images/Contmatic.png" class="d-block w-100 h-100" alt="...">
			<div class="carousel-caption d-none d-md-block">
				<h5>Second slide label</h5>
				<p>Some representative placeholder content for the second slide.</p>
			</div>
		</div>
		<div class="carousel-item" data-bs-interval="5000">
			<img src="/images/WhatsappWeb.png" class="d-block w-100 h-100" alt="...">
			<div class="carousel-caption d-none d-md-block">
				<h5>Third slide label</h5>
				<p>Some representative placeholder content for the third slide.</p>
			</div>
		</div>
	</div>
	<button class="carousel-control-prev" type="button" data-bs-target="#carouselAplicativos" data-bs-slide="prev">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="visually-hidden">Previous</span>
	</button>
	<button class="carousel-control-next" type="button" data-bs-target="#carouselAplicativos" data-bs-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="visually-hidden">Next</span>
	</button>
</div>

AlvesMello_IntraNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Alves & Mello</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/AlvesMello_IntraNet.styles.css" asp-append-version="true" />
</head>
<body>
	<header class="p-3 bg-dark text-white">
		<div class="container">
			<div class="d-flex justify-content-between">
				<div class="d-flex align-items-center">
					<div>
						<a href="https://www.alvesemello.com.br" class="d-flex my-2 my-lg-0 text-decoration-none" style="border: solid 2px #6c757d; border-radius: 4px;">
							<img class="logo-image" src="~/images/A&M.png" />
						</a>
					</div>

					<ul class="nav col-12 col-lg-auto text-small">
						<li>
							<a class="nav-link px-2 text-secondary" asp-area="" asp-controller="Home" asp-action="Index">
								<img class="header-icons bi d-block mx-auto mb-1" src="~/images/Home.png" />
								Home
							</a>
						</li>
						@if (User.IsInRole("Admin"))
						{
							<li>
								<a class="nav-link px-2 text-white" asp-area="Admin" asp-controller="Admin" asp-action="Index">
									<img class="header-icons bi d-block mx-auto mb-1" src="~/images/Administration.png" />
									Admin
								</a>
							</li>
						}
						<li>
							@await Component.InvokeAsync("DepartmentMenu")
						</li>
						<li>
							<a class="nav-link px-2 text-white" asp-area="" asp-controller="TelephoneExtension" asp-action="Index">
								<img class="header-icons bi d-block mx-auto mb-1" src="~/images/TelephoneExtension.png" />
								Ramais
							</a>
						</li>
						<li>
							<a class="nav-link px-2 text-white" asp-area="" asp-controller="Birthday" asp-action="Index">
								<img class="header-icons bi d-block mx-auto mb-1" src="~/images/Birthday.png" />
								Aniversários
							</a>
						</li>
						<li>
							<a class="nav-link px-2 text-white" asp-area="" asp-controller="Contact" asp-action="Index">
								<img class="header-icons bi d-block mx-auto mb-1" src="~/images/SendEmail.png" />
								Contato
							</a>
						</li>
					</ul>
				</div>

				<div class="d-flex align-items-center">
					<form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" asp-controller="Site" asp-action="Search" method="get">
						<input type="search" class="form-control form-control-dark" placeholder="Procurar Site" name="searchString" value="@ViewData["searchString"]" aria-label="Search">
					</form>

					@await Html.PartialAsync("_LoginPartial")
				</div>
			</div>
		</div>
	</header>
	<br />

	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted bg-dark">
		<div class="container">
			&copy; Alves & Mello - IntraNet - 2022
		</div>
	</footer>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AlvesMello_IntraNet/Views/Shared/_SitesSummary.cshtml
@model Site

<div class="col-sm-4 col-md-4 col-lg-4">
	<a href="@Model.SiteUrl">
		<p><img src="@Model.ImageUrl" class="img-fluid" style="width: 410px; height: 200px;" /></p>
	</a>

	<h4>
		<a asp-controller="Site" asp-action="Details" asp-route-siteId="@Model.SiteId">@Model.Name</a>
	</h4>

	<h5>
		<form asp-controller="Site" asp-action="List" asp-route-department="@Model.Department.Name">
			<button class="btn" style="background-color: @Model.Department.Color; color: white">
				@Model.Department.Name
			</button>
		</form>
	</h5>

	<p>@Model.Description</p>

	<div>
		<p class="button">
			<a class="btn btn-primary" id="favButton" asp-controller="FavoriteSite" asp-action="AddSiteToFavoriteSite" asp-route-siteId="@Model.SiteId">
				Incluir aos Favoritos
			</a>
		</p>
	</div>
</div>