AlvesMello_IntraNet/Areas/Admin/Controllers/AdminSitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AlvesMello_IntraNet.Context;
using AlvesMello_IntraNet.Models;
using Microsoft.AspNetCore.Authorization;
using ReflectionIT.Mvc.Paging;

namespace AlvesMello_IntraNet.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminSitesController : Controller
    {
        private readonly AppDbContext _context;

        public AdminSitesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminSites
        public async Task<IActionResult> Index(string filter, int pagindex = 1, string sort = "Name")
        {
            var result = _context.Sites.Include(s => s.Department).AsQueryable();

            if (!string.IsNullOrWhiteSpace(filter))
            {
                result = result.Where(p => p.Name.Contains(filter));
            }

            var model = await PagingList.CreateAsync(result, 5, pagindex, sort, "Name");
            model.RouteValue = new RouteValueDictionary { { "filter", filter } };
            return View(model);
        }

        // GET: Admin/AdminSites/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Sites == null)
            {
                return NotFound();
            }

            var site = await _context.Sites
                .Include(s => s.Department)
                .FirstOrDefaultAsync(m => m.SiteId == id);
            if (site == null)
            {
                return NotFound();
            }

            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "Name", site.DepartmentId);
            return View(site);
        }

        // GET: Admin/AdminSites/Create
        public IActionResult Create()
        {
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "Name");
            return View();
        }

        // POST: Admin/AdminSites/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SiteId,Name,Description,ImageUrl,SiteUrl,IsFavorite,IsActive,DepartmentId")] Site site)
        {
            if (ModelState.IsValid)
            {
                _context.Add(site);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "Name", site.DepartmentId);
            return View(site);
        }

        // GET: Admin/AdminSites/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Sites == null)
            {
                return NotFound();
            }

            var site = await _context.Sites.FindAsync(id);
            if (site == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "Name", site.DepartmentId);
            return View(site);
        }

        // POST: Admin/AdminSites/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SiteId,Name,Description,ImageUrl,SiteUrl,IsFavorite,IsActive,DepartmentId")] Site site)
        {
            if (id != site.SiteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(site);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SiteExists(site.SiteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "Name", site.DepartmentId);
            return View(site);
        }

        // GET: Admin/AdminSites/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Sites == null)
            {
                return NotFound();
            }

            var site = await _context.Sites
                .Include(s => s.Department)
                .FirstOrDefaultAsync(m => m.SiteId == id);
            if (site == null)
            {
                return NotFound();
            }

            return View(site);
        }

        // POST: Admin/AdminSites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Sites == null)
            {
                return Problem("Entity set 'AppDbContext.Sites'  is null.");
            }
            var site = await _context.Sites.FindAsync(id);
            if (site != null)
            {
                _context.Sites.Remove(site);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SiteExists(int id)
        {
          return _context.Sites.Any(e => e.SiteId == id);
        }
    }
}

AlvesMello_IntraNet/Areas/Admin/Views/AdminSites/Create.cshtml
@model AlvesMello_IntraNet.Models.Site

@{
	ViewData["Title"] = "Adicionar Site";
}

<h1>Adicionar Site</h1>
<hr />

<div class="container">
	<div class="row">
		<div class="col-12">
			<form asp-action="Create">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group">
					<label asp-for="Name" class="control-label"></label>
					<input asp-for="Name" class="form-control" />
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<br />

				<div class="form-group">
					<label asp-for="Description" class="control-label"></label>
					<textarea asp-for="Description" class="form-control"></textarea>
					<span asp-validation-for="Description" class="text-danger"></span>
				</div>
				<br />

				<div class="d-flex">
					<div class="col-6">
						<label asp-for="ImageUrl" class="control-label"></label>
						<input asp-for="ImageUrl" class="form-control" />
						<span asp-validation-for="ImageUrl" class="text-danger"></span>
					</div>
					<div class="col-1">
					</div>
					<div class="col-5">
						<div class="col-12">
							<label>Prévia da Imagem</label>
						</div>
						<div class="col-12">
							<image class="img-thumbnail" src="/images/ECAC.png" style="max-height: 200px" id="previewImage" />
						</div>
					</div>
				</div>
				<br />

				<div class="col-12">
					<label asp-for="SiteUrl" class="control-label"></label>
					<input asp-for="SiteUrl" class="form-control" />
					<span asp-validation-for="SiteUrl" class="text-danger"></span>
				</div>
				<br />

				<div class="d-flex">
					<div class="col-4">
						<label asp-for="DepartmentId" class="control-label"></label>
					</div>
					<div class="col-2">
					</div>
					<div class="col-3">
						<label class="form-check-label">Marcar como Favorito</label>
					</div>
					<div class="col-3">
						<label class="form-check-label">Marcar como Ativo</label>
					</div>
				</div>

				<div class="d-flex">
					<div class="col-4">
						<select asp-for="DepartmentId" class="btn border-dark dropdown-toggle col-12" asp-items="ViewBag.DepartmentId"></select>
					</div>
					<div class="col-2">
					</div>
					<div class="col-3">
						<input class="form-check-input" asp-for="IsFavorite" /> @Html.DisplayNameFor(model => model.IsFavorite)
					</div>
					<div class="col-3">
						<input class="form-check-input checked" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
					</div>
				</div>
				<br />

				<div class="col-12">
					<div class="d-flex">
						<div class="col-1">
							<div class="form-group">
								<input type="submit" value="Adicionar" class="btn btn-primary" />
							</div>
						</div>
						<div class="col-1">
							<div>
								<a class="btn btn-secondary" asp-area="Admin" asp-controller="AdminSites" asp-action="Index">Voltar</a>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

AlvesMello_IntraNet/Areas/Admin/Views/AdminSites/Delete.cshtml
@model AlvesMello_IntraNet.Models.Site

@{
    ViewData["Title"] = "Deletar Site";
}

<h1>Deletar Site</h1>

<h3>Você tem certeza que deseja deletar esse Site?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            Imagem do Site
        </dt>
        <dd class = "col-sm-10">
            <image class="img-thumbnail" src="@Model.ImageUrl" style="max-height: 200px"/>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SiteUrl)
        </dt>
        <dd class = "col-sm-10">
            <a href="@Model.SiteUrl">
                @Html.DisplayFor(model => model.SiteUrl)
            </a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            <div class="d-flex text-center text-light">
				<div class="rounded-pill p-2 " style="background-color: @Html.DisplayFor(model => model.Department.Color)">
					@Html.DisplayFor(model => model.Department.Name)
				</div>
			</div>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsFavorite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsFavorite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SiteId" />
        <input type="submit" value="Deletar" class="btn btn-danger" />
        <a class="btn btn-secondary" asp-action="Index">Voltar para a Listagem</a>
    </form>
</div>

AlvesMello_IntraNet/Areas/Admin/Views/AdminSites/Details.cshtml
@model AlvesMello_IntraNet.Models.Site

@{
    ViewData["Title"] = "Detalhes do Site";
}

<h1>Detalhes do Site</h1>

<div>
    <h4>Id do Site: @Model.SiteId</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            Imagem do Site
        </dt>
        <dd class = "col-sm-10">
            <image class="img-thumbnail" src="@Model.ImageUrl" style="max-height: 200px"/>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SiteUrl)
        </dt>
        <dd class = "col-sm-10">
            <a href="@Model.SiteUrl">
                @Html.DisplayFor(model => model.SiteUrl)
            </a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            <div class="d-flex text-center text-light">
				<div class="rounded-pill p-2 " style="background-color: @Html.DisplayFor(model => model.Department.Color)">
					@Html.DisplayFor(model => model.Department.Name)
				</div>
			</div>            
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsFavorite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsFavorite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
</div>
<div>
	<a class="btn btn-dark" asp-action="Edit" asp-route-id="@Model?.SiteId">Editar Site</a>
	<a class="btn btn-secondary" asp-action="Index">Voltar para a Listagem</a>
</div>

AlvesMello_IntraNet/Areas/Admin/Views/AdminSites/Edit.cshtml
@model AlvesMello_IntraNet.Models.Site

@{
	ViewData["Title"] = "Editar Site";
}

<h1>Editar Site</h1>
<hr />

<div class="container">
	<div class="row">
		<div class="col-12">
			<form asp-action="Edit">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<input type="hidden" asp-for="SiteId" />

				<div class="form-group">
					<label asp-for="Name" class="control-label"></label>
					<input asp-for="Name" class="form-control" />
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<br />

				<div class="form-group">
					<label asp-for="Description" class="control-label"></label>
					<textarea asp-for="Description" class="form-control"></textarea>
					<span asp-validation-for="Description" class="text-danger"></span>
				</div>
				<br />

				<div class="d-flex">
					<div class="col-6">
						<label asp-for="ImageUrl" class="control-label"></label>
						<input asp-for="ImageUrl" class="form-control" />
						<span asp-validation-for="ImageUrl" class="text-danger"></span>
					</div>
					<div class="col-1">
					</div>
					<div class="col-5">
						<div class="col-12">
							<label>Prévia da Imagem</label>
						</div>
						<div class="col-12">
							@if (string.IsNullOrWhiteSpace(@Model.ImageUrl))
							{
								<image class="img-thumbnail" src="/images/ECAC.png" style="max-height: 200px" id="previewImage" />
							} else
							{
								<image class="img-thumbnail" src="@Model.ImageUrl" style="max-height: 200px" id="previewImage" />
							}
						</div>
					</div>
				</div>
				<br />

				<div class="col-12">
					<label asp-for="SiteUrl" class="control-label"></label>
					<input asp-for="SiteUrl" class="form-control" />
					<span asp-validation-for="SiteUrl" class="text-danger"></span>
				</div>
				<br />

				<div class="d-flex">
					<div class="col-4">
						<label asp-for="DepartmentId" class="control-label"></label>
					</div>
					<div class="col-2">
					</div>
					<div class="col-3">
						<label class="form-check-label">Marcar como Favorito</label>
					</div>
					<div class="col-3">
						<label class="form-check-label">Marcar como Ativo</label>
					</div>
				</div>

				<div class="d-flex">
					<div class="col-4">
						<select asp-for="DepartmentId" class="btn border-dark dropdown-toggle col-12" asp-items="ViewBag.DepartmentId"></select>
					</div>
					<div class="col-2">
					</div>
					<div class="col-3">
						<input class="form-check-input" asp-for="IsFavorite" /> @Html.DisplayNameFor(model => model.IsFavorite)
					</div>
					<div class="col-3">
						<input class="form-check-input checked" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
					</div>
				</div>
				<br />

				<div class="col-12">
					<div class="d-flex">
						<div class="col-1">
							<div class="form-group">
								<input type="submit" value="Salvar" class="btn btn-primary" />
							</div>
						</div>
						<div class="col-1">
							<div>
								<a class="btn btn-secondary" asp-area="Admin" asp-controller="AdminSites" asp-action="Index">Voltar</a>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<br />

AlvesMello_IntraNet/Areas/Admin/Views/AdminSites/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<AlvesMello_IntraNet.Models.Site>

@{
	ViewData["Title"] = "Listagem de Sites";
}

<h1>Sites</h1>

<form method="get" class="form-inline">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="input-group">
					<div class="input-group-btn">
						<button type="button" class="btn btn-dark dropdown-toggle" data-toggle="dropdown"> Nome <span class="caret"></span></button>

						<ul class="dropdown-menu">
							<li>
								<a>Nome</a>
							</li>
						</ul>
					</div>

					<div class="form-group col-10">
						<input name="filter" type="text" class="form-control" maxlength="100" value="@Model.RouteValue["Filter"]">
					</div>

					<div class="input-group-btn">
						<button type="submit" class="btn btn-danger">
							<image src="/images/Search.png"></image>
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>
<br />

<div>
	<vc:pager paging-list="@Model"></vc:pager>
</div>

<div class="row">
	<div class="col-md-12">
		<table class="table">
			<thead>
				<tr>
					<th>
						Imagem do Site
					</th>
					<th>
						@Html.DisplayNameFor(model => model.Name)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.SiteUrl)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.Department)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.IsFavorite)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.IsActive)
					</th>
					<th>

					</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>
							<image class="img-thumbnail" src="@item.ImageUrl" style="max-height: 200px" />
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Name)
						</td>
						<td>
							<a href="@item.SiteUrl">@item.SiteUrl</a>
						</td>
						<td style="color: white">
							<div class="d-flex justify-content-evenly text-center">
								<div class="rounded-pill p-2 " style="background-color: @item.Department.Color">
									@Html.DisplayFor(modelItem => item.Department.Name)
								</div>
							</div>
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.IsFavorite)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.IsActive)
						</td>
						<td>
							<div class="d-flex flex-wrap justify-content-evenly">
								<div>
									<a class="btn btn-dark" asp-action="Edit" asp-route-id="@item.SiteId">Editar</a>
								</div>
								<div>
									<a class="btn btn-secondary" asp-action="Details" asp-route-id="@item.SiteId">Detalhes</a>
								</div>
								<div>
									<a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.SiteId">Deletar</a>
								</div>
							</div>
						</td>
					</tr>
				}
			</tbody>
		</table>

		<div class="row">
			<div class="col-6">
				<a class="btn btn-success" asp-action="Create">
					Adicionar Site
				</a>
			</div>

			<div class="col-6 d-flex justify-content-end">
				Total de Sites: @Model.TotalRecordCount
			</div>
		</div>
	</div>
</div>