AlvesMello_IntraNet/Areas/Admin/Controllers/AdminImagesController.cs
using AlvesMello_IntraNet.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace AlvesMello_IntraNet.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "Admin")]
public class AdminImagesController : Controller
{
    private readonly ConfigurationImages _myConfig;
    private readonly IWebHostEnvironment _hostingEnvironment;

    public AdminImagesController(IWebHostEnvironment hostingEnvironment,
        IOptions<ConfigurationImages> myConfiguration)
    {
        _hostingEnvironment = hostingEnvironment;
        _myConfig = myConfiguration.Value;
    }

    public IActionResult Index()
    {
        return View();
    }

    public async Task<IActionResult> UploadFiles(List<IFormFile> files)
    {
		if (files == null || files.Count == 0)
		{
            ViewData["Erro"] = "Erro: Arquivo(s) não selecionado(s)";
            return View(ViewData);
		}

		if (files.Count > 100)
		{
            ViewData["Erro"] = "Erro: Quantidade de arquivos excedeu o limite";
            return View(ViewData);
		}

        long size = files.Sum(f => f.Length);

        var filePathsName = new List<string>();

        var filePath = Path.Combine(_hostingEnvironment.WebRootPath,
            _myConfig.FolderNameImagesSites);

		foreach (var formFile in files)
		{
			if (formFile.FileName.Contains(".jpg") 
                || formFile.FileName.Contains(".gif")
                || formFile.FileName.Contains(".png"))
			{
                var fileNameWithPath = string.Concat(filePath, "\\", formFile.FileName);
                filePathsName.Add(fileNameWithPath);

                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
				{
                    await formFile.CopyToAsync(stream);
				}
            }
		}

        ViewData["Result"] = $"{files.Count} arquivos foram enviados ao servidor, " +
            $"com o tamanho total de: {size} bytes";

        ViewBag.Files = filePathsName;

        return View(ViewData);
    }

    public IActionResult GetImages()
    {
        FileManagerModel model = new FileManagerModel();

        var userImagesPath = Path.Combine(_hostingEnvironment.WebRootPath, _myConfig.FolderNameImagesSites);

        DirectoryInfo dir = new DirectoryInfo(userImagesPath);

        FileInfo[] files = dir.GetFiles();

        model.PathImagesSite = _myConfig.FolderNameImagesSites;

        if (files.Length == 0)
        {
            ViewData["Erro"] = $"Nenhum arquivo encontrado na pasta {userImagesPath}";
        }

        model.Files = files;

        return View(model);
    }

    public IActionResult DeleteFile(string fname)
    {
        string _imageDelete = Path.Combine(_hostingEnvironment.WebRootPath, _myConfig.FolderNameImagesSites + "\\", fname);

        if (System.IO.File.Exists(_imageDelete))
        {
            System.IO.File.Delete(_imageDelete);

            ViewData["Deleted"] = $"Arquivo(s) {_imageDelete} deletado com sucesso";
        }

        return View("index");
    }
}

AlvesMello_IntraNet/Areas/Admin/Views/AdminImages/GetImages.cshtml
@model FileManagerModel

@{
	ViewBag.Title = "Arquivos";
}

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

@if (Model.Files != null)
{
	<section class="ftco-section pt-4">
		<div class="container">
			<div class="row justify-content-center mb-3">
				<div class="col-md-7 heading-section text-center ftco-animate fadeInUp ftco-animated">
					<h2>Arquivos no Servidor</h2>
				</div>
			</div>
			<hr />

			<div class="d-flex">
				<div class="me-2">
					<button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
						Enviar Arquivos
					</button>
					<ul class="dropdown-menu">
						<li>
							<button class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#uploadModal">
								<image src="/images/PNG.png" width="32px" height="32px"></image>
								Imagem PNG, JPG ou GIF
							</button>
						</li>
						<li>
							<a class="dropdown-item" href="#">
								<image src="/images/MP4.png" width="32px" height="32px"></image>
								Vídeo MP4
							</a>
						</li>
						<li>
							<a class="dropdown-item" href="#">
								<image src="/images/PDF.png" width="32px" height="32px"></image>
								Importar PDF
							</a>
						</li>
					</ul>
				</div>
			</div>
			<br />

			<div class="row">
				@foreach (FileInfo file in Model.Files)
				{
					var path = Model.PathImagesSite;

					<div class="col-md-4 ftco-animate fadeInUp ftco-animated">
						<div class="block-7 border">
							<div>
								<image class="img border border-dark" src="/@path/@file.Name"></image>
							</div>
							<div class="text-center p-4">
								<span class="excerpt d-block">@file.Name</span>
								<br />

								<button id="delete" data-bs-toggle="modal" data-bs-target="#confirmationModal" data-bs-name="@file.Name" data-bs-link="@Url.Action("DeleteFile", "AdminImages", new { fname=file.Name })" class="btn btn-danger d-block px-2 py-3">Deletar</button>
							</div>
						</div>
					</div>
				}
			</div>
		</div>
	</section>
}

@*Modals*@
<body id="deleteModal">
	<div id="confirmationModal" tabindex="-1" class="modal fade" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered modal-confirm">
			<div class="modal-content">
				<div class="modal-header">
					<div class="icon-box d-flex justify-content-center align-items-lg-center">
						<image src="/images/X.png"></image>
					</div>
					<button type="button" class="close" data-bs-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div>
					<h4 id="modalTitle" class="modal-title">Você tem certeza?</h4>
				</div>
				<div class="modal-body">
					<p> Deseja deletar a imagem selecionada? Esse processo não pode ser desfeito.</p>
				</div>
				<div class="modal-footer d-flex justify-content-center">
					<a id="deleteConfirmation" class="btn btn-danger">Deletar</a>
					<button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancelar</button>
				</div>
			</div>
		</div>
	</div>
</body>

<body>
	<div id="uploadModal" tabindex="-1" class="modal fade" role="dialog" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered">
			<div class="modal-content">
				<div class="modal-header d-flex justify-content-end">
					<button type="button" class="close" data-bs-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div>
					<div class="d-flex justify-content-center">
						<image src="/images/UploadImages.png" width="200" height="200" alt="Upload de Imagens" />
					</div>
					<form method="post" enctype="multipart/form-data" asp-controller="AdminImages" asp-action="UploadFiles">
						<div class="form-group">
							<div>
								<h4 id="modalTitle" class="modal-title">Selecione um ou mais arquivos para enviar</h4>
								<p>(Arquivos com o mesmo nome serão sobrescritos)</p>
								<input type="file" name="files" multiple class="button btn-outline-primary" />
							</div>
							<br />

							<div class="modal-footer d-flex justify-content-center">
								<button type="submit" class="btn btn-outline-primary">Enviar Arquivo(s)</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</body>

<script type="text/javascript">
	var confirmationModal = document.getElementById('confirmationModal')
	confirmationModal.addEventListener('show.bs.modal', function(event) {

		// Button that triggered the modal
		var button = event.relatedTarget

		// Extract info from data-bs-* attributes
		var imageName = button.getAttribute('data-bs-name')
		var imagePath = button.getAttribute('data-bs-link')

		// Update the modal's content.
		var modalTitle = confirmationModal.querySelector('.modal-title')

		modalTitle.textContent = imageName
		$("a.btn").prop("href", imagePath)
	})
</script>

<style>
	.ftco-section {
		border-radius: 4px;
		background-color: #e1e3db;
	}

	.block-7 {
		border-radius: 4px;
		margin-bottom: 30px;
		padding: 0;
		overflow: hidden;
		background: #fff;
		-webkit-box-shadow: 0px 24px 48px -13px rgba(0, 0, 0, 0.05);
		-moz-box-shadow: 0px 24px 48px -13px rgba(0, 0, 0, 0.05);
		box-shadow: 0px 24px 48px -13px rgba(0, 0, 0, 0.05);
		-moz-transition: all 0.3s ease;
		-o-transition: all 0.3s ease;
		-webkit-transition: all 0.3s ease;
		transition: all 0.3s ease;
	}

		.block-7 .img {
			height: 250px;
			width: 100%;
		}

		.block-7 .heading-2 {
			font-size: 14px;
			text-transform: uppercase;
			letter-spacing: 1px;
			font-weight: 600;
		}

		.block-7 .excerpt {
			margin-bottom: 0px;
			color: black;
			font-size: 16px;
			font-weight: 600;
			text-transform: uppercase;
		}

		.block-7 .label2 {
			text-transform: uppercase;
		}

		.block-7 .btn-danger {
			color: #fff;
			text-transform: uppercase;
			font-weight: 600;
			letter-spacing: 1px;
			width: 60%;
			margin: 0 auto;
		}

			.block-7 .btn-danger:hover,
			.block-7 .btn-danger:focus {
				background: #b02a37 !important;
				color: #fff;
			}

		.block-7:hover,
		.block-7:focus {
			-webkit-box-shadow: 0px 24px 48px -13px rgba(0, 0, 0, 0.11);
			-moz-box-shadow: 0px 24px 48px -13px rgba(0, 0, 0, 0.11);
			box-shadow: 0px 24px 48px -13px rgba(0, 0, 0, 0.11);
		}

	/*Confirmation Modal*/
	.modal-title {
		text-transform: uppercase;
	}

	.modal-confirm {
		color: #636363;
		width: 400px;
		margin: 30px auto;
	}

		.modal-dialog .modal-content {
			padding: 20px;
			border-radius: 5px;
			border: none;
			text-align: center;
			font-size: 14px;
		}

		.modal-header {
			border-bottom: none;
			position: relative;
		}

		.modal-confirm h4 {
			text-align: center;
			font-size: 26px;
		}

		.modal-dialog .close {
			position: absolute;
			top: -5px;
			right: -2px;
			font-size: 24px;
			background: none;
			border: none;
			font-weight: 600
		}

		.modal-dialog .modal-body {
			color: #999;
		}

		.modal-dialog .modal-footer {
			border: none;
			text-align: center;
			border-radius: 5px;
			font-size: 13px;
			padding: 10px 15px 25px;
		}

		.modal-confirm .icon-box {
			width: 80px;
			height: 80px;
			margin: 0 auto;
			border-radius: 50%;
			z-index: 9;
			text-align: center;
			border: 3px solid #f15e5e;
		}

			.modal-confirm .icon-box i {
				color: #f15e5e;
				font-size: 46px;
				display: inline-block;
				margin-top: 13px;
			}

		.modal-dialog .btn {
			color: #fff;
			border-radius: 4px;
			background: #60c7c1;
			text-decoration: none;
			transition: all 0.4s;
			line-height: normal;
			min-width: 120px;
			border: none;
			min-height: 40px;
			border-radius: 3px;
			margin: 0 5px;
			outline: none !important;
		}

		.modal-confirm .btn-info {
			background: #c1c1c1;
		}

			.modal-confirm .btn-info:hover, .modal-confirm .btn-info:focus {
				background: #a8a8a8;
			}

		.modal-confirm .btn-danger {
			background: #f15e5e;
		}

			.modal-confirm .btn-danger:hover, .modal-confirm .btn-danger:focus {
				background: #ee3535;
			}
</style>

AlvesMello_IntraNet/Areas/Admin/Views/AdminImages/Index.cshtml
<table border="0" width="100%">
	<tr>
		<td>
			<form method="post" enctype="multipart/form-data" asp-controller="AdminImages" asp-action="GetImages">
				<div class="d-flex justify-content-center">
					<image class="m-3" src="/images/ViewImages.png" width="200" height="200" />

					<div class="form-group">
						<div class="col-md-10">
							<p><strong>Visualizar Imagens na Pasta do Servidor </strong></p>
						</div>
						<br />

						<div class="form-group">
							<div class="col-md-10">
								<input type="submit" value="Visualizar Arquivos no Servidor" class="button btn-outline-warning" />
							</div>
						</div>
					</div>
				</div>
			</form>
		</td>
	</tr>
</table>

<div class="container">
	@if (ViewData["Deleted"] != null)
	{
		<div>
			@ViewData["Deleted"]
		</div>
	}
</div>

AlvesMello_IntraNet/Areas/Admin/Views/AdminImages/UploadFiles.cshtml
@{
	ViewData["Title"] = "UploadFiles";
}

<image src="" widht="200" height="150"/>
<hr />

<div class="jumbotron jumbotron-fluid">
	<div class="container">
		@if (ViewData["Erro"] != null)
		{
			<image src="" widht="150" height="150"/>
			<h4>@ViewData["Erro"]</h4>
		}
	</div>

	<div class="container">
		@if (ViewData["Result"] != null)
		{
			<h4>@ViewData["Result"]</h4>
			<hr />

			@if (ViewBag.Files != null)
			{
				@foreach (string file in ViewBag.Files)
				{
					<div>
						@file
					</div>
				}
			}
		}
	</div>
</div>